site_name: PPG-beats

nav:
    - 'Home': 'index.md'
    - 'Toolbox':
      - 'Getting Started': './toolbox/getting_started.md'
      - 'PPG Beat Detectors': './toolbox/ppg_beat_detectors.md'
      - 'ECG Beat Detectors': './toolbox/ecg_beat_detectors.md'
      - 'Performance Assessment': './toolbox/performance_assessment.md'
    - 'Datasets':
      - 'Summary': './datasets/summary.md'
      - 'BIDMC': './datasets/bidmc.md'
      - 'CapnoBase': './datasets/capnobase.md'
      - 'MIMIC AF Subset': './datasets/mimic_af_subset.md'
      - 'MIMIC Ethnicity Subset': './datasets/mimic_ethnicity_subset.md'
      - 'MIMIC PERform Training': './datasets/mimic_perform_training.md'
      - 'MIMIC PERform Testing': './datasets/mimic_perform_testing.md'
      - 'PPG-DaLiA': './datasets/ppg_dalia.md'
      - 'WESAD': './datasets/wesad.md'
    - 'Functions':
      - 'align_ppg_ecg_beats': './functions/align_ppg_ecg_beats.md'
      - 'assess_multiple_datasets': './functions/assess_multiple_datasets.md'
      - 'assess_beat_detectors': './functions/assess_beat_detectors.md'
      - 'preprocess_ppg_signal': './functions/preprocess_ppg_signal.md'
      - 'detect_ppg_beats': './functions/detect_ppg_beats.md'
      - 'detect_ecg_beats': './functions/detect_ecg_beats.md'
      - 'atmax_beat_detector': './functions/atmax_beat_detector.md'
      - 'atmin_beat_detector': './functions/atmin_beat_detector.md'
      - 'abd_beat_detector': './functions/abd_beat_detector.md'
      - 'ampd_beat_detector': './functions/ampd_beat_detector.md'
      - 'coppg_beat_detector': './functions/coppg_beat_detector.md'
      - 'erma_beat_detector': './functions/erma_beat_detector.md'
      - 'heartpypc_beat_detector': './functions/heartpypc_beat_detector.md'
      - 'ims_beat_detector': './functions/ims_beat_detector.md'
      - 'msptd_beat_detector': './functions/msptd_beat_detector.md'
      - 'pda_beat_detector': './functions/pda_beat_detector.md'
      - 'ppgpulses_beat_detector': './functions/ppgpulses_beat_detector.md'
      - 'pwd_beat_detector': './functions/pwd_beat_detector.md'
      - 'qppg_beat_detector': './functions/qppg_beat_detector.md'
      - 'qppgfast_beat_detector': './functions/qppgfast_beat_detector.md'
      - 'spar_beat_detector': './functions/spar_beat_detector.md'
      - 'swt_beat_detector': './functions/swt_beat_detector.md'
      - 'wfd_beat_detector': './functions/wfd_beat_detector.md'
    - 'Tutorials':
      - 'Summary': './tutorials/summary.md'
      - 'PPG Beat Detection': './tutorials/ppg_beat_detection.md'
      - 'Performance Assessment': './tutorials/performance_assessment.md'
      - 'ECG Beat Detection': './tutorials/ecg_beat_detection.md'
      - 'Time Alignment': './tutorials/time_alignment.md'
      - 'Creating Documentation': './tutorials/creating_docs.md'
    