site_name: PPG-beats
repo_url: https://github.com/peterhcharlton/ppg-beats

nav:
    - 'Home': 'index.md'
    - 'Getting Started': './getting_started/index.md'
    - 'Algorithms':
      - 'PPG Beat Detection': './algorithms/ppg_beat_detection_algs.md'
      - 'ECG Beat Detection': './algorithms/ecg_beat_detection_algs.md'
    - 'Assessing Performance':
      - 'Datasets': './assessing_performance/datasets/index.md'
      - 'Code': './assessing_performance/code/index.md'
    - 'Tutorials':
      - 'PPG Beat Detection': './tutorials/beat_detection/ppg_beat_detection.md'
      - 'ECG Beat Detection': './tutorials/beat_detection/ecg_beat_detection.md'
      - 'Performance Assessment': './tutorials/performance_assessment/index.md'
      - 'Time Alignment': './tutorials/misc/time_alignment.md'