site_name: PPG-beats
repo_url: https://github.com/peterhcharlton/ppg-beats

nav:
    - 'Home': 'index.md'
    - 'Getting Started': './getting_started.md'
    - 'Toolbox':
      - 'Datasets': './datasets.md'
      - 'Performance Assessment': './code.md'
      - 'PPG Beat Detection': './ppg_beat_detection_algs.md'
      - 'ECG Beat Detection': './ecg_beat_detection_algs.md'
      - 'Functions':
        - 'assess_multiple_datasets': './functions/assess_multiple_datasets.md'
        - 'assess_beat_detectors': './functions/assess_beat_detectors.md'
        - 'preprocess_ppg_signal': './functions/preprocess_ppg_signal.md'
        - 'detect_ppg_beats': './functions/detect_ppg_beats.md'
        - 'abd_beat_detector': './functions/abd_beat_detector.md'
        - 'ampd_beat_detector': './functions/ampd_beat_detector.md'
        - 'coppg_beat_detector': './functions/coppg_beat_detector.md'
        - 'erma_beat_detector': './functions/erma_beat_detector.md'
        - 'heartpypc_beat_detector': './functions/heartpypc_beat_detector.md'
        - 'ims_beat_detector': './functions/ims_beat_detector.md'
        - 'msptd_beat_detector': './functions/msptd_beat_detector.md'
        - 'pda_beat_detector': './functions/pda_beat_detector.md'
        - 'ppgpulses_beat_detector': './functions/ppgpulses_beat_detector.md'
        - 'pwd_beat_detector': './functions/pwd_beat_detector.md'
        - 'qppg_beat_detector': './functions/qppg_beat_detector.md'
        - 'qppgfast_beat_detector': './functions/qppgfast_beat_detector.md'
        - 'spar_beat_detector': './functions/spar_beat_detector.md'
        - 'wfd_beat_detector': './functions/wfd_beat_detector.md'
    - 'Tutorials':
      - 'PPG Beat Detection': './tutorials/ppg_beat_detection.md'
      - 'ECG Beat Detection': './tutorials/ecg_beat_detection.md'
      - 'Performance Assessment': './tutorials/performance_assessment.md'
      - 'Time Alignment': './tutorials/time_alignment.md'
      