site_name: PPG-beats
repo_url: https://github.com/peterhcharlton/ppg-beats
edit_uri: ''
site_description: PPG-beats, a Matlab library of algorithms to detect heartbeats in photoplethysmogram (PPG) signals
site_author: Peter H Charlton
copyright: Made available under the <a href = "https://creativecommons.org/licenses/by/4.0/">CC BY 4.0 license</a>

nav:
    - 'Home': 'index.md'
    - 'Toolbox':
      - 'Getting Started': './toolbox/getting_started.md'
      - 'PPG Beat Detectors': './toolbox/ppg_beat_detectors.md'
      - 'ECG Beat Detectors': './toolbox/ecg_beat_detectors.md'
      - 'Performance Assessment': './toolbox/performance_assessment.md'
      - 'Contributing': './toolbox/contributing.md'
      - 'Acknowledgments': './toolbox/acknowledgments.md'
    - 'Datasets':
      - 'Summary': './datasets/summary.md'
      - 'CapnoBase': './datasets/capnobase.md'
      - 'BIDMC': './datasets/bidmc.md'
      - 'MIMIC PERform Training': './datasets/mimic_perform_training.md'
      - 'MIMIC PERform Testing': './datasets/mimic_perform_testing.md'
      - 'MIMIC PERform AF': './datasets/mimic_perform_af.md'
      - 'MIMIC PERform Ethnicity': './datasets/mimic_perform_ethnicity.md'
      - 'PPG-DaLiA': './datasets/ppg_dalia.md'
      - 'WESAD': './datasets/wesad.md'
    - 'Functions':
      - 'detect_ppg_beats': './functions/detect_ppg_beats.md'
      - 'detect_ecg_beats': './functions/detect_ecg_beats.md'
      - 'assess_beat_detectors': './functions/assess_beat_detectors.md'
      - 'assess_multiple_datasets': './functions/assess_multiple_datasets.md'
      - 'preprocess_ppg_signal': './functions/preprocess_ppg_signal.md'
      - 'align_ppg_ecg_beats': './functions/align_ppg_ecg_beats.md'
      - 'abd_beat_detector': './functions/abd_beat_detector.md'
      - 'ampd_beat_detector': './functions/ampd_beat_detector.md'
      - 'atmax_beat_detector': './functions/atmax_beat_detector.md'
      - 'atmin_beat_detector': './functions/atmin_beat_detector.md'
      - 'coppg_beat_detector': './functions/coppg_beat_detector.md'
      - 'erma_beat_detector': './functions/erma_beat_detector.md'
      - 'heartpy_beat_detector': './functions/heartpy_beat_detector.md'
      - 'ims_beat_detector': './functions/ims_beat_detector.md'
      - 'msptd_beat_detector': './functions/msptd_beat_detector.md'
      - 'pda_beat_detector': './functions/pda_beat_detector.md'
      - 'ppgpulses_beat_detector': './functions/ppgpulses_beat_detector.md'
      - 'pwd_beat_detector': './functions/pwd_beat_detector.md'
      - 'qppg_beat_detector': './functions/qppg_beat_detector.md'
      - 'qppgfast_beat_detector': './functions/qppgfast_beat_detector.md'
      - 'spar_beat_detector': './functions/spar_beat_detector.md'
      - 'swt_beat_detector': './functions/swt_beat_detector.md'
      - 'wfd_beat_detector': './functions/wfd_beat_detector.md'
      - 'collate_mimic_perform_train_test_datasets': './functions/collate_mimic_perform_train_test_datasets.md'
      - 'collate_mimic_perform_af_dataset': './functions/collate_mimic_perform_af_dataset.md'
      - 'collate_mimic_perform_ethnicity_dataset': './functions/collate_mimic_perform_ethnicity_dataset.md'
      - 'mimic_perform_dataset_converter': './functions/mimic_perform_dataset_converter.md'
      - 'export_sample_mimic_perform_data': './functions/export_sample_mimic_perform_data.md'
    - 'Tutorials':
      - 'Summary': './tutorials/summary.md'
      - 'PPG Beat Detection': './tutorials/ppg_beat_detection.md'
      - 'Performance Assessment': './tutorials/performance_assessment.md'
      - 'ECG Beat Detection': './tutorials/ecg_beat_detection.md'
      - 'Time Alignment': './tutorials/time_alignment.md'
      - 'Creating Documentation': './tutorials/creating_docs.md'
