[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ppg-beats"
authors = [{name = "Peter H Charlton", email = "abc"}]
dynamic = ["version", "description"]
